### ISSUE TITLE
Forms without labels

### ISSUE THREAD

**Issue by claudioccm** [ccmdesign/360-ds#6]
```
# Subscribe
<input placeholder="Subscribe to our newsletter" id="EMAIL" name="EMAIL" type="email">

# Search
<input type="search" class="search-field <!-- js-search-filter -->" name="s" id="s" placeholder="Search" value="">
```

Solution
---

```<label for="id" class=" screen-reader-only "> Label text </label>```

**Comment by DouglasCantao** [comment]
Cláudio

adicionei os labels.
utilizei o css disponível neste site.
https://accessibility.18f.gov/hidden-content/

**Comment by claudioccm** [comment]
O CSS eu adicionei aqui https://github.com/ccmdesign/360-ds/issues/7

**Comment by DouglasCantao** [comment]
Blz Cláudio.

Removi o css dos components. Agora ta utilizando do utils, que você adicionou.
